AWSTemplateFormatVersion: '2010-09-09'
Description: Cognito User Pool and User Pool Client

Parameters:
  Environment:
    Type: String
  PreSignUpArn:
    Type: String
  PostAuthArn:
    Type: String

Resources:
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub "todo-user-pool-${Environment}"
      UsernameAttributes: [email]
      AutoVerifiedAttributes: [email]
      Schema:
        - Name: email
          Required: true
          Mutable: true
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false
      LambdaConfig:
        PreSignUp: !Ref PreSignUpArn
        PostAuthentication: !Ref PostAuthArn

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub "todo-app-client-${Environment}"
      UserPoolId: !Ref UserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_SRP_AUTH

  PreSignUpCognitoPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref PreSignUpArn
      Action: lambda:InvokeFunction
      Principal: cognito-idp.amazonaws.com
      SourceArn: !GetAtt UserPool.Arn

  PostAuthCognitoPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref PostAuthArn
      Action: lambda:InvokeFunction
      Principal: cognito-idp.amazonaws.com
      SourceArn: !GetAtt UserPool.Arn

Outputs:
  UserPoolId:
    Value: !Ref UserPool
  UserPoolArn:
    Value: !GetAtt UserPool.Arn
  UserPoolClientId:
    Value: !Ref UserPoolClient
